In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
features_autoencoder =  pd.read_csv('/content/drive/MyDrive/Data/prepared data/features_autoencoder.csv')
features_denoise_comb = pd.read_csv('/content/drive/MyDrive/Data/prepared data/features_denoising_comb.csv')
features_denoise_mask = pd.read_csv('/content/drive/MyDrive/Data/prepared data/features_denoising_mask.csv')
features_denoise_gauss = pd.read_csv('/content/drive/MyDrive/Data/prepared data/features_denoising_gaussian.csv')
data2 = pd.read_csv('/content/drive/MyDrive/Data/prepared data/volunteer_2022_labelled.csv')
resonance_features = pd.read_csv('/content/drive/MyDrive/Data/prepared data/resonance_features.csv')

In [3]:
resonance_features = resonance_features.rename(columns={'File Path': 'kept_paths'})

In [4]:
print(data2.columns)

Index(['Volunteer number', 'Age', 'Gender', 'Height[m]', 'Weight[kg]', 'BMI',
       'HGS_Left', 'HGS_Right', 'Comorbidity_Index', 'SARC-F_Score',
       'Skin[mm]', 'Fat[mm]', 'Rfcsa[cm2]'],
      dtype='object')

In [5]:
data2.drop(['Comorbidity_Index','SARC-F_Score'], axis=1, inplace=True)

In [6]:
data2["volunteer"] = "Volunteer_" + (data2.reset_index().index + 1).astype(str)

In [7]:
data2.drop(['Volunteer number'],axis=1, inplace=True)

In [8]:
data2

,Age,Gender,Height[m],Weight[kg],BMI,HGS_Left,HGS_Right,Skin[mm],Fat[mm],Rfcsa[cm2],volunteer
0,42,M,1.77,102.0,32.557694,"26,32, 28","36,36,40",2.00,9.00,3.12,Volunteer_1
1,51,M,1.78,69.0,21.777553,"41, 40,40","42, 38, 40",2.13,1.40,4.87,Volunteer_2
2,26,F,1.56,62.0,25.476660,"33,30, 28","28,30, 30",1.80,10.10,5.90,Volunteer_3
3,34,F,1.63,55.0,20.700817,"22, 23, 24","25, 25, 22",1.30,21.63,3.19,Volunteer_4
4,27,F,1.56,78.0,32.051282,"27, 26, 24","25, 30, 29",1.53,22.40,1.64,Volunteer_5
5,33,M,1.75,94.0,30.693878,"52, 48, 38","49, 46, 44",1.63,11.23,3.95,Volunteer_6
6,28,M,1.82,89.4,26.989494,"49,48, 46","50, 52,53",1.83,6.73,9.63,Volunteer_7
7,30,F,1.67,65.0,23.306680,"30, 27, 27","28, 31, 26",1.37,12.37,2.87,Volunteer_8
8,29,F,1.73,64.0,21.383942,"28, 26, 24","28, 27, 28",1.67,13.37,3.97,Volunteer_9
9,24,F,1.64,56.0,20.820940,"26,30, 27","30,30 28",1.40,11.60,3.84,Volunteer_10
10,23,F,1.65,57.0,20.936639,"26, 26, 24","23,27,28",1.37,12.60,3.79,Volunteer_11
11,27,M,1.72,70.0,23.661439,"29,29,25","28,25,26",1.70,8.63,5.11,Volunteer_12
12,39,M,1.73,91.3,30.505530,"46, 44, 42","52, 51, 47",1.73,9.00,5.00,Volunteer_13
13,24,M,1.98,80.0,20.406081,"46, 44, 44","50, 46, 48",1.87,4.60,4.29,Volunteer_14
14,28,F,1.58,61.6,24.675533,"27,26, 26","27, 28, 27",1.37,12.83,3.01,Volunteer_15
15,27,M,1.78,84.0,26.511804,"48, 48, 46","44, 45, 40",2.33,9.60,3.10,Volunteer_16
16,30,M,1.84,96.0,28.355388,"42, 45, 36","46,46, 43",2.00,6.03,9.92,Volunteer_17
17,36,M,1.72,98.0,NaN,"50,48,46","52,50,48",2.50,9.40,4.26,Volunteer_18

In [9]:
df_joined_autoencode = pd.merge(features_autoencoder, data2, on="volunteer", how="inner")
df_joined_denoise_comb = pd.merge(features_denoise_comb, data2, on="volunteer", how="inner")
df_joined_denoise_mask = pd.merge(features_denoise_mask, data2, on="volunteer", how="inner")
df_joined_denoise_gauss = pd.merge(features_denoise_gauss, data2, on="volunteer", how="inner")

In [10]:
df_joined_autoencode = pd.merge(df_joined_autoencode, resonance_features, on="kept_paths", how="inner")
df_joined_denoise_comb = pd.merge(df_joined_denoise_comb, resonance_features, on="kept_paths", how="inner")
df_joined_denoise_mask = pd.merge(df_joined_denoise_mask, resonance_features, on="kept_paths", how="inner")
df_joined_denoise_gauss = pd.merge(df_joined_denoise_gauss, resonance_features, on="kept_paths", how="inner")

In [11]:
df_joined_denoise_mask

,volunteer,device,kept_paths,mu,sigma,feat_0,feat_1,feat_2,feat_3,feat_4,...,Device,Bandstop Frequency,Bandstop Magnitude,f_left,f_right,BW,Threshold,Phase_1GHz_deg,Phase_2GHz_deg,Slope
0,Volunteer_2,miniVNA,/content/drive/MyDrive/Data/MAS Volunteer Stud...,14.766270,15.069767,0.446924,0.629466,0.0,0.562808,0.639906,...,miniVNA,2.113887,-53.592093,2.113483,2.114410,0.000927,-48.592093,75.244532,-94.598662,1000.994370
1,Volunteer_2,miniVNA,/content/drive/MyDrive/Data/MAS Volunteer Stud...,14.959881,14.846529,0.446028,0.626661,0.0,0.561045,0.640219,...,miniVNA,2.115801,-32.681858,2.114363,2.117106,0.002742,-27.681858,74.774876,-93.783474,986.025190
2,Volunteer_2,miniVNA,/content/drive/MyDrive/Data/MAS Volunteer Stud...,15.484674,14.381699,0.446752,0.625106,0.0,0.558322,0.638685,...,miniVNA,2.110059,-28.939183,2.108985,2.113408,0.004423,-23.939183,81.261525,-99.025696,986.902038
3,Volunteer_2,miniVNA,/content/drive/MyDrive/Data/MAS Volunteer Stud...,12.637120,17.162884,0.443270,0.624127,0.0,0.563092,0.639357,...,miniVNA,2.986601,-37.468497,2.985850,2.987960,0.002110,-32.468497,104.621732,94.971091,251.003068
4,Volunteer_2,miniVNA,/content/drive/MyDrive/Data/MAS Volunteer Stud...,15.139236,14.704661,0.448259,0.628755,0.0,0.563027,0.642392,...,miniVNA,1.997142,-25.318124,1.990638,2.006956,0.016318,-20.318124,97.311359,NaN,827.248473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,Volunteer_15,CopperMountain,/content/drive/MyDrive/Data/MAS Volunteer Stud...,-17.736612,8.743196,0.454643,0.634676,0.0,0.560176,0.632985,...,CopperMountain,2.141229,-39.855128,2.134443,2.149337,0.014894,-34.855128,-387.180292,-50.234066,690.501162
472,Volunteer_15,CopperMountain,/content/drive/MyDrive/Data/MAS Volunteer Stud...,-17.504323,8.671565,0.453854,0.631518,0.0,0.557634,0.629657,...,CopperMountain,2.148228,-39.864984,2.141299,2.156387,0.015088,-34.864984,-386.717471,-51.936233,697.794745
473,Volunteer_15,CopperMountain,/content/drive/MyDrive/Data/MAS Volunteer Stud...,-59.568125,8.925476,0.488736,0.675863,0.0,0.565145,0.632867,...,CopperMountain,1.847238,-81.658308,1.816358,1.939016,0.122658,-76.658308,-1342.280292,NaN,-180.762562
474,Volunteer_15,CopperMountain,/content/drive/MyDrive/Data/MAS Volunteer Stud...,-59.386537,9.055461,0.492965,0.686923,0.0,0.574438,0.640532,...,CopperMountain,1.825239,-82.244093,1.822873,1.827156,0.004283,-77.244093,-2042.245340,NaN,-197.161668
475,Volunteer_15,CopperMountain,/content/drive/MyDrive/Data/MAS Volunteer Stud...,-59.248960,9.115996,0.491287,0.685902,0.0,0.573640,0.640842,...,CopperMountain,1.859238,-84.318765,1.858331,1.860722,0.002392,-79.318765,-1350.578284,NaN,-163.176352

In [12]:
output_dir = '/content/drive/MyDrive/Data/prepared data'
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, 'autoencoder_dataset.csv')
df_joined_autoencode.to_csv(output_path, index=False)
print(f"Features DataFrame saved to {output_path}")

output_dir = '/content/drive/MyDrive/Data/prepared data'
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, 'de_autoencoder_comb_dataset.csv')
df_joined_denoise_comb.to_csv(output_path, index=False)
print(f"Features DataFrame saved to {output_path}")

output_dir = '/content/drive/MyDrive/Data/prepared data'
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, 'de_autoencoder_mask_dataset.csv')
df_joined_denoise_mask.to_csv(output_path, index=False)
print(f"Features DataFrame saved to {output_path}")

output_dir = '/content/drive/MyDrive/Data/prepared data'
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, 'de_autoencoder_gauss_dataset.csv')
df_joined_denoise_gauss.to_csv(output_path, index=False)
print(f"Features DataFrame saved to {output_path}")

Features DataFrame saved to /content/drive/MyDrive/Data/prepared data/autoencoder_dataset.csv
Features DataFrame saved to /content/drive/MyDrive/Data/prepared data/de_autoencoder_comb_dataset.csv
Features DataFrame saved to /content/drive/MyDrive/Data/prepared data/de_autoencoder_mask_dataset.csv
Features DataFrame saved to /content/drive/MyDrive/Data/prepared data/de_autoencoder_gauss_dataset.csv